openapi: 3.0.0
info:
  title: OpenStorage SDK OpenStorageAlerts OpenStorageClusterDomains API
  version: 0.186.0
security:
- bearerAuth: []
tags:
- name: OpenStorageClusterDomains
paths:
  /v1/clusterdomains:
    get:
      operationId: OpenStorageClusterDomains_Enumerate
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkClusterDomainsEnumerateResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: Enumerate returns names of all the cluster domains in the cluster
      tags:
      - OpenStorageClusterDomains
  /v1/clusterdomains/activate/{cluster_domain_name}:
    post:
      operationId: OpenStorageClusterDomains_Activate
      parameters:
      - description: Name of the cluster domain to activate
        in: path
        name: cluster_domain_name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkClusterDomainActivateResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: 'Activates a cluster domain in the cluster.

        All the nodes which are part of an active cluster domain

        will participate in cluster quorum calculation'
      tags:
      - OpenStorageClusterDomains
  /v1/clusterdomains/deactivate/{cluster_domain_name}:
    post:
      operationId: OpenStorageClusterDomains_Deactivate
      parameters:
      - description: Name of the cluster domain to deactivate
        in: path
        name: cluster_domain_name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkClusterDomainDeactivateResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: 'Deactivates a cluster domain in the cluster.

        All the nodes which are part of a deactivated cluster domain.

        will not participate in cluster quorum calculation'
      tags:
      - OpenStorageClusterDomains
  /v1/clusterdomains/inspect/{cluster_domain_name}:
    get:
      operationId: OpenStorageClusterDomains_Inspect
      parameters:
      - description: Name of the cluster domain to inspect
        in: path
        name: cluster_domain_name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkClusterDomainInspectResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: 'Inspect returns information about a cluster domain and a

        status indicating whether the cluster domain is active'
      tags:
      - OpenStorageClusterDomains
components:
  schemas:
    protobufAny:
      properties:
        type_url:
          type: string
        value:
          format: byte
          type: string
      type: object
    apiSdkClusterDomainsEnumerateResponse:
      properties:
        cluster_domain_names:
          items:
            type: string
          title: List of names of all the cluster domains in a cluster
          type: array
      title: Defines a response when enumerating cluster domains
      type: object
    apiSdkClusterDomainActivateResponse:
      title: Empty response
      type: object
    runtimeError:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
        error:
          type: string
        message:
          type: string
      type: object
    apiSdkClusterDomainDeactivateResponse:
      title: Empty response
      type: object
    apiSdkClusterDomainInspectResponse:
      properties:
        cluster_domain_name:
          title: Name of the cluster domain
          type: string
        is_active:
          title: IsActive indicates whether this cluster domain is active
          type: boolean
      title: Defines a response to inspecting a cluster domain
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
