openapi: 3.0.0
info:
  title: OpenStorage SDK OpenStorageAlerts OpenStorageFilesystemCheck API
  version: 0.186.0
security:
- bearerAuth: []
tags:
- name: OpenStorageFilesystemCheck
paths:
  /v1/filesystem-check/delete-snapshots:
    post:
      operationId: OpenStorageFilesystemCheck_DeleteSnapshots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/apiSdkFilesystemCheckDeleteSnapshotsRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckDeleteSnapshotsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: Delete all fsck created snapshots on volume
      tags:
      - OpenStorageFilesystemCheck
  /v1/filesystem-check/list-snapshots:
    get:
      operationId: OpenStorageFilesystemCheck_ListSnapshots
      parameters:
      - description: Id of the volume.
        in: query
        name: volume_id
        required: false
        schema:
          type: string
      - description: Node Id of the volume.
        in: query
        name: node_id
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckListSnapshotsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: List all fsck created snapshots on volume
      tags:
      - OpenStorageFilesystemCheck
  /v1/filesystem-check/list-volumes:
    get:
      operationId: OpenStorageFilesystemCheck_ListVolumes
      parameters:
      - description: Node Id filter.
        in: query
        name: node_id
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckListVolumesResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: List of all volumes which require fsck check/fix to be run
      tags:
      - OpenStorageFilesystemCheck
  /v1/filesystem-check/start:
    post:
      operationId: OpenStorageFilesystemCheck_Start
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/apiSdkFilesystemCheckStartRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckStartResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: Start a filesystem-check background operation on a unmounted volume.
      tags:
      - OpenStorageFilesystemCheck
  /v1/filesystem-check/status:
    get:
      operationId: OpenStorageFilesystemCheck_Status
      parameters:
      - description: Id of the volume.
        in: query
        name: volume_id
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckStatusResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: 'Get Status of a filesystem-check background operation on an unmounted

        volume, if any'
      tags:
      - OpenStorageFilesystemCheck
  /v1/filesystem-check/stop:
    post:
      operationId: OpenStorageFilesystemCheck_Stop
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/apiSdkFilesystemCheckStopRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkFilesystemCheckStopResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: Stop a filesystem check background operation on an unmounted volume, if any
      tags:
      - OpenStorageFilesystemCheck
components:
  schemas:
    apiSdkFilesystemCheckStopResponse:
      title: Empty response
      type: object
    protobufAny:
      properties:
        type_url:
          type: string
        value:
          format: byte
          type: string
      type: object
    apiSdkFilesystemCheckStopRequest:
      properties:
        volume_id:
          title: Id of the volume
          type: string
      title: 'SdkFilesystemCheckStopRequest defines a request to stop a background

        filesystem check operation'
      type: object
    apiSdkFilesystemCheckStatusResponse:
      description: 'SdkFilesystemCheckStatusResponse defines the response for a

        SdkFilesystemCheckStatusRequest.'
      properties:
        health_status:
          $ref: '#/components/schemas/apiFilesystemHealthStatus'
        message:
          title: Text blob containing ASCII text providing details of the operation
          type: string
        mode:
          title: Text string representing the mode of filesystem check operation
          type: string
        status:
          $ref: '#/components/schemas/FilesystemCheckFilesystemCheckStatus'
      type: object
    FilesystemCheckFilesystemCheckStatus:
      default: FS_CHECK_UNKNOWN
      description: "- FS_CHECK_UNKNOWN: Filesystem Check operation is an unknown state\n - FS_CHECK_NOT_RUNNING: FilesystemCheck operation not running for the specified volume\n - FS_CHECK_STARTED: FilesystemCheck operation started for the specified volume\n - FS_CHECK_INPROGRESS: FilesystemCheck operation is in progress\n - FS_CHECK_STOPPED: FilesystemCheck operation was stopped by the user\n - FS_CHECK_COMPLETED: FilesystemCheck operation completed successfully\n - FS_CHECK_FAILED: FilesystemCheck operation failed due to internal error"
      enum:
      - FS_CHECK_UNKNOWN
      - FS_CHECK_NOT_RUNNING
      - FS_CHECK_STARTED
      - FS_CHECK_INPROGRESS
      - FS_CHECK_STOPPED
      - FS_CHECK_COMPLETED
      - FS_CHECK_FAILED
      title: 'FilesystemCheckStatus represents the status codes returned from

        OpenStorageFilesystemCheck service APIs()'
      type: string
    apiSdkFilesystemCheckListSnapshotsResponse:
      properties:
        snapshots:
          additionalProperties:
            $ref: '#/components/schemas/apiFilesystemCheckSnapInfo'
          title: Map of volume snapshot ids and snapshot info
          type: object
      title: 'SdkFilesystemCheckListSnapshotsResponse defines a response to list

        snapshots created by fsck for a volume'
      type: object
    apiSdkFilesystemCheckDeleteSnapshotsRequest:
      properties:
        node_id:
          title: Node Id filter
          type: string
        volume_id:
          title: Id of the volume
          type: string
      title: 'SdkFilesystemCheckDeleteSnapshotsRequest defines a request to delete

        snapshots created by fsck for a volume'
      type: object
    runtimeError:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
        error:
          type: string
        message:
          type: string
      type: object
    apiFilesystemCheckSnapInfo:
      properties:
        volume_snapshot_name:
          title: Name of the snapshot
          type: string
      title: 'FilesystemCheckSnapInfo contains the volume snapshot info for

        filesystem check list snapshots operation'
      type: object
    apiSdkFilesystemCheckListVolumesResponse:
      properties:
        volumes:
          additionalProperties:
            $ref: '#/components/schemas/apiFilesystemCheckVolInfo'
          title: Map of volume ids and volume info
          type: object
      title: 'SdkFilesystemCheckListVolumesResponse defines a response to list

        all volumes needing fsck check/fix'
      type: object
    apiSdkFilesystemCheckDeleteSnapshotsResponse:
      title: 'SdkFilesystemCheckDeleteSnapshotsResponse defines a respone to delete

        snapshots created by fsck for a volume'
      type: object
    apiSdkFilesystemCheckStartResponse:
      description: 'SdkFilesystemCheckStartResponse defines the response for a

        SdkFilesystemCheckStartRequest.'
      properties:
        message:
          title: Text blob containing ASCII text providing details of the operation
          type: string
        status:
          $ref: '#/components/schemas/FilesystemCheckFilesystemCheckStatus'
      type: object
    apiFilesystemCheckVolInfo:
      properties:
        fs_status_msg:
          title: FS status detailed message
          type: string
        health_status:
          $ref: '#/components/schemas/apiFilesystemHealthStatus'
        volume_name:
          title: Name of the volume
          type: string
      title: 'FilesystemCheckVolInfo contains the volume info for

        filesystem check list volumes operation'
      type: object
    apiSdkFilesystemCheckStartRequest:
      properties:
        mode:
          title: Mode of operation
          type: string
        volume_id:
          title: Id of the volume
          type: string
      title: 'SdkFilesystemCheckStartRequest defines a request to start a background

        filesystem consistency check operation'
      type: object
    apiFilesystemHealthStatus:
      default: FS_HEALTH_STATUS_UNKNOWN
      enum:
      - FS_HEALTH_STATUS_UNKNOWN
      - FS_HEALTH_STATUS_HEALTHY
      - FS_HEALTH_STATUS_SAFE_TO_FIX
      - FS_HEALTH_STATUS_NEEDS_INSPECTION
      title: "- FS_HEALTH_STATUS_UNKNOWN: filesystem health status is unknown\n - FS_HEALTH_STATUS_HEALTHY: filesystem is a healthy\n - FS_HEALTH_STATUS_SAFE_TO_FIX: filesystem has errors, but can be fixed safely\n - FS_HEALTH_STATUS_NEEDS_INSPECTION: filesystem has errors, these cannot be fixed automatically,\nuser needs to review the reported errors and take appropriate action"
      type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
