openapi: 3.0.0
info:
  title: OpenStorage SDK OpenStorageAlerts OpenStorageIdentity API
  version: 0.186.0
security:
- bearerAuth: []
tags:
- name: OpenStorageIdentity
paths:
  /v1/identities/capabilities:
    get:
      operationId: OpenStorageIdentity_Capabilities
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkIdentityCapabilitiesResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: 'Capabilities returns the supported services by the cluster.

        This allows SDK implementations to advertise their supported

        services as the API matures. With this information, clients

        can determine supported services from storage clusters at

        different versions.'
      tags:
      - OpenStorageIdentity
  /v1/identities/version:
    get:
      operationId: OpenStorageIdentity_Version
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiSdkIdentityVersionResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
          description: An unexpected error response.
      summary: Version returns version information about the system.
      tags:
      - OpenStorageIdentity
components:
  schemas:
    apiStorageVersion:
      properties:
        details:
          additionalProperties:
            type: string
          title: Extra information provided by the storage system
          type: object
        driver:
          title: OpenStorage driver name
          type: string
        version:
          title: Version of the server
          type: string
      title: Version information about the storage system
      type: object
    protobufAny:
      properties:
        type_url:
          type: string
        value:
          format: byte
          type: string
      type: object
    apiSdkVersion:
      description: 'SDK version in Major.Minor.Patch format. The goal of this

        message is to provide clients a method to determine the SDK

        version run by an SDK server.'
      properties:
        major:
          format: int32
          title: SDK version major number
          type: integer
        minor:
          format: int32
          title: SDK version minor number
          type: integer
        patch:
          format: int32
          title: SDK version patch number
          type: integer
        version:
          description: 'String representation of the SDK version. Must be

            in `major.minor.patch` format.'
          type: string
      type: object
    apiSdkIdentityCapabilitiesResponse:
      properties:
        capabilities:
          items:
            $ref: '#/components/schemas/apiSdkServiceCapability'
          title: Provides all the capabilities supported by the cluster
          type: array
      title: Defines a response containing the capabilities of the cluster
      type: object
    runtimeError:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
        error:
          type: string
        message:
          type: string
      type: object
    apiSdkIdentityVersionResponse:
      properties:
        sdk_version:
          $ref: '#/components/schemas/apiSdkVersion'
        version:
          $ref: '#/components/schemas/apiStorageVersion'
      title: Defines a response containing version information
      type: object
    apiSdkServiceCapability:
      properties:
        service:
          $ref: '#/components/schemas/SdkServiceCapabilityOpenStorageService'
      title: Defines a capability of he cluster
      type: object
    SdkServiceCapabilityOpenStorageServiceType:
      default: UNKNOWN
      enum:
      - UNKNOWN
      - CLUSTER
      - CLOUD_BACKUP
      - CREDENTIALS
      - NODE
      - OBJECT_STORAGE
      - SCHEDULE_POLICY
      - VOLUME
      - ALERTS
      - MOUNT_ATTACH
      - ROLE
      - CLUSTER_PAIR
      - MIGRATE
      - STORAGE_POLICY
      title: "- UNKNOWN: Unknown service\n - CLUSTER: Cluster management\n - CLOUD_BACKUP: Cloud backup of volumes management\n - CREDENTIALS: Credentials management\n - NODE: Node management\n - OBJECT_STORAGE: Object Storage management\n - SCHEDULE_POLICY: Schedule policy management\n - VOLUME: Volume management\n - ALERTS: Alert enumeration\n - MOUNT_ATTACH: Mount/Attach Support\n - ROLE: Role service\n - CLUSTER_PAIR: Cluster Pair service\n - MIGRATE: Migrate service\n - STORAGE_POLICY: StoragePolicy Service"
      type: string
    SdkServiceCapabilityOpenStorageService:
      properties:
        type:
          $ref: '#/components/schemas/SdkServiceCapabilityOpenStorageServiceType'
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
